# -*- coding: utf-8 -*-
"""
Master assembly script for the IARS dissertation.

Reads:
  - subagent-drafted chapter text files from docs/chapter_drafts/*.txt
    (chapter2.txt, chapter3_design.txt, chapter3_impl.txt, chapter4.txt, chapter6.txt)
  - content_owned.py (Chapter 1, Chapter 5, References, Appendices - authored directly)
  - dissertation_assets/*.png (diagrams generated by generate_diagrams.py)

Produces: docs/IARS-Dissertation.docx
"""
import os
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

from docx_helpers import (
    new_document, start_new_section, add_page_break, add_chapter_title,
    add_paragraph_text, add_toc_field, render_chapter_markdown,
    add_table_caption_with_tc, add_markdown_table, ASSETS_DIR,
)
from content_owned import (
    CH1_INTRODUCTION, CH5_CONCLUSION, REFERENCES,
    APPENDIX_A, APPENDIX_B, APPENDIX_C, APPENDIX_D, APPENDIX_E, APPENDIX_F,
)

DRAFTS_DIR = os.path.join(os.path.dirname(__file__), "chapter_drafts")

FIGURE_MAP = {}
for fname in os.listdir(ASSETS_DIR):
    if fname.endswith(".png") and not fname.startswith("placeholder_"):
        FIGURE_MAP[fname[:-4]] = os.path.join(ASSETS_DIR, fname)
FIGURE_MAP["SCREENSHOT"] = None  # forces labeled placeholder per-call


def load_draft(name):
    path = os.path.join(DRAFTS_DIR, name)
    if not os.path.exists(path):
        raise FileNotFoundError("Missing chapter draft: %s" % path)
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def render_with_screenshot_placeholders(doc, text, base_figure_map):
    """Chapter 6 uses a shared 'SCREENSHOT' placeholder id per figure; give
    each one a distinct placeholder image keyed by its caption text."""
    lines = text.replace("\r\n", "\n").split("\n")
    pending_caption = None
    local_map = dict(base_figure_map)
    counter = 0
    out_lines = []
    for line in lines:
        if line.strip().upper().startswith("FIGURE_CAPTION:"):
            pending_caption = line.split(":", 1)[1].strip()
            out_lines.append(line)
        elif line.strip().upper().startswith("FIGURE_PLACEHOLDER:") and "SCREENSHOT" in line.upper():
            counter += 1
            key = "SCREENSHOT_%d" % counter
            local_map[key] = None
            out_lines.append("FIGURE_PLACEHOLDER: " + key)
        else:
            out_lines.append(line)
    render_chapter_markdown(doc, "\n".join(out_lines), local_map)


# ---------------------------------------------------------------------
# FRONT MATTER
# ---------------------------------------------------------------------

def build_front_matter(doc):
    sec = start_new_section(doc, header_text=None, footer_page_fmt="roman", first_section=True)
    # remove footer page number on the title page itself
    for p in sec.footer.paragraphs:
        p.text = ""

    # --- Title Page ---
    for _ in range(3):
        doc.add_paragraph()
    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = t.add_run("INTELLIGENT ACCOMMODATION REVIEW SYSTEM (IARS)")
    r.font.name = "Arial"; r.font.size = Pt(20); r.font.bold = True
    t2 = doc.add_paragraph()
    t2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r2 = t2.add_run("A MERN-Stack Accommodation Booking Platform with Sentiment-Aware Reviews\nand a Hybrid Recommendation Engine")
    r2.font.name = "Arial"; r2.font.size = Pt(13); r2.font.italic = True
    for _ in range(4):
        doc.add_paragraph()
    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    rs = sub.add_run("Final Year Project Dissertation\nsubmitted in partial fulfilment of the requirements for the\ndegree of Bachelor of Science in Computer Science")
    rs.font.name = "Times New Roman"; rs.font.size = Pt(12)
    for _ in range(4):
        doc.add_paragraph()
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    rm = meta.add_run("Submitted by:\n[Student Name] — [Registration / Roll No.]\n\nSupervised by:\n[Supervisor Name]\n\nDepartment of Computer Science\n[University Name]\n[Month, Year]")
    rm.font.name = "Times New Roman"; rm.font.size = Pt(12)
    add_page_break(doc)

    # --- Approval / Final Approval Page ---
    doc.add_paragraph("FINAL APPROVAL", style="FrontMatterHeading")
    add_paragraph_text(doc, "This project report titled **\"Intelligent Accommodation Review System (IARS)\"**, submitted by the student named on the title page, has been evaluated and is hereby approved for submission in partial fulfilment of the requirements for the degree of Bachelor of Science in Computer Science.")
    for _ in range(2):
        doc.add_paragraph()
    for label in ["Internal Examiner", "External Examiner", "Supervisor"]:
        p = doc.add_paragraph()
        p.add_run("_______________________________          ").font.size = Pt(12)
        p.add_run(label)
        p.paragraph_format.space_after = Pt(28)
    add_page_break(doc)

    # --- Certificate ---
    doc.add_paragraph("CERTIFICATE", style="FrontMatterHeading")
    add_paragraph_text(doc, "This is to certify that the project work titled **\"Intelligent Accommodation Review System (IARS)\"** has been carried out and completed under my supervision. To the best of my knowledge, the work presented in this report is an accurate description of the system implemented by the student and is approved for submission for evaluation.")
    for _ in range(3):
        doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("_______________________________")
    p2 = doc.add_paragraph("Supervisor's Signature and Date")
    add_page_break(doc)

    # --- Acknowledgement ---
    doc.add_paragraph("ACKNOWLEDGEMENT", style="FrontMatterHeading")
    add_paragraph_text(doc, "I would like to express my sincere gratitude to my project supervisor for the guidance, feedback, and encouragement provided throughout the development of this project. I am also thankful to the faculty of the Department of Computer Science for the knowledge and skills imparted during the course of my studies, which formed the foundation for this work. Finally, I am grateful to my family and friends for their continuous support and patience throughout this project.")
    add_page_break(doc)

    # --- Declaration ---
    doc.add_paragraph("DECLARATION", style="FrontMatterHeading")
    add_paragraph_text(doc, "I hereby declare that this project report, titled \"Intelligent Accommodation Review System (IARS),\" and the work presented in it are my own. I confirm that the system described has been designed and implemented by me, that any material drawn from external sources has been properly referenced, and that this work has not been submitted, in whole or in part, for any other degree or qualification at this or any other institution.")
    for _ in range(3):
        doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run("_______________________________")
    p2 = doc.add_paragraph("Student's Signature and Date")
    add_page_break(doc)

    # --- Abstract ---
    doc.add_paragraph("ABSTRACT", style="FrontMatterHeading")
    add_paragraph_text(doc, "The Intelligent Accommodation Review System (IARS) is a web-based accommodation booking platform that combines a conventional search-and-book workflow with sentiment-aware review analysis, heuristic image verification, and a hybrid property-recommendation engine. Built on the MERN stack — MongoDB, Express.js, React.js, and Node.js — and supported by a dedicated Python FastAPI microservice for sentiment classification, IARS allows guests to search approved property listings, book online through Stripe's test-mode checkout or submit a form-based offline request, and leave reviews that are automatically classified by sentiment and broken down by aspect (cleanliness, staff, location, and others). Property owners can create and edit listings and upload up to five images per property, each of which is checked for duplication and given a heuristic quality score before being queued for administrator review; a listing cannot be approved until at least one of its images has been marked verified. A recommendation engine combines Bayesian-smoothed quality scoring, content-based similarity, and collaborative filtering derived from a guest's booking, viewing, and search history to personalise the properties shown to returning guests, while new or anonymous visitors receive a quality-ranked cold-start selection. The interface supports English, Urdu, and Arabic, with automatic right-to-left layout adaptation for the latter two languages. This report documents the system's requirements, architecture, database schema, API design, implementation, and testing, and evaluates the sentiment, recommendation, and image-verification subsystems against the objectives defined at the outset of the project.")
    add_page_break(doc)

    # --- Project in Brief ---
    doc.add_paragraph("PROJECT IN BRIEF", style="FrontMatterHeading")
    rows = [
        ["Item", "Details"],
        ["Project Title", "Intelligent Accommodation Review System (IARS)"],
        ["Team", "[Student Name] — [Registration / Roll No.]"],
        ["Supervisor", "[Supervisor Name]"],
        ["Start Date", "[Start Date]"],
        ["Completion Date", "[Completion Date]"],
        ["Frontend", "React 18, Vite, Tailwind CSS, shadcn/ui, react-router-dom, i18next"],
        ["Backend", "Node.js, Express.js, Mongoose"],
        ["Database", "MongoDB"],
        ["AI / ML Component", "Python, FastAPI, scikit-learn (TF-IDF + Logistic Regression)"],
        ["Payment Integration", "Stripe API (test mode)"],
        ["Languages Supported", "English (default, LTR), Urdu (RTL), Arabic (RTL)"],
        ["Tools", "Git, VS Code, Postman, MongoDB Compass"],
    ]
    add_markdown_table(doc, rows)
    add_page_break(doc)

    # --- Table of Contents ---
    doc.add_paragraph("TABLE OF CONTENTS", style="FrontMatterHeading")
    add_toc_field(doc, ' TOC \\o "1-3" \\h \\z \\u ')
    add_page_break(doc)

    # --- List of Figures ---
    doc.add_paragraph("LIST OF FIGURES", style="FrontMatterHeading")
    add_toc_field(doc, ' TOC \\f f \\c "f" ')
    add_page_break(doc)

    # --- List of Tables ---
    doc.add_paragraph("LIST OF TABLES", style="FrontMatterHeading")
    add_toc_field(doc, ' TOC \\f t \\c "t" ')


# ---------------------------------------------------------------------
# MAIN ASSEMBLY
# ---------------------------------------------------------------------

def main():
    doc = new_document()
    build_front_matter(doc)

    chapters = [
        ("CHAPTER 1", "INTRODUCTION", CH1_INTRODUCTION, None),
        ("CHAPTER 2", "SYSTEM ANALYSIS", None, "chapter2.txt"),
        ("CHAPTER 3", "SYSTEM DESIGN AND IMPLEMENTATION", None, ["chapter3_design.txt", "chapter3_impl.txt"]),
        ("CHAPTER 4", "SYSTEM TESTING", None, "chapter4.txt"),
        ("CHAPTER 5", "CONCLUSION AND FUTURE WORK", CH5_CONCLUSION, None),
        ("CHAPTER 6", "USER INTERFACE", None, "chapter6.txt"),
    ]

    for idx, (label, title, owned_text, draft_file) in enumerate(chapters):
        restart = 1 if idx == 0 else None
        start_new_section(doc, header_text="IARS \u00b7 %s" % label.title(),
                           footer_page_fmt="decimal", restart_at=restart)
        add_chapter_title(doc, label, title)
        if owned_text is not None:
            render_chapter_markdown(doc, owned_text, FIGURE_MAP)
        else:
            if isinstance(draft_file, list):
                combined = "\n\n".join(load_draft(f) for f in draft_file)
            else:
                combined = load_draft(draft_file)
            if label == "CHAPTER 6":
                render_with_screenshot_placeholders(doc, combined, FIGURE_MAP)
            else:
                render_chapter_markdown(doc, combined, FIGURE_MAP)

    # Chapter 7 - References
    start_new_section(doc, header_text="IARS \u00b7 Chapter 7", footer_page_fmt="decimal")
    add_chapter_title(doc, "CHAPTER 7", "REFERENCES")
    for i, ref in enumerate(REFERENCES, start=1):
        p = doc.add_paragraph()
        p.paragraph_format.left_indent = Inches(0.4)
        p.paragraph_format.first_line_indent = Inches(-0.4)
        run = p.add_run("[%d] " % i)
        run.bold = True
        p.add_run(ref)

    # Appendices
    start_new_section(doc, header_text="IARS \u00b7 Appendices", footer_page_fmt="decimal")
    doc.add_paragraph("APPENDICES", style="Heading 1")
    appendix_sections = [
        ("Appendix A: Environment Setup and Installation Guide", APPENDIX_A),
        ("Appendix B: Full API Endpoint Reference", APPENDIX_B),
        ("Appendix C: Complete Database Schema Listing", APPENDIX_C),
        ("Appendix D: Sentiment Model and Training Data Details", APPENDIX_D),
        ("Appendix E: Additional UI Screenshots", APPENDIX_E),
        ("Appendix F: Full Test Case Execution Log", APPENDIX_F),
    ]
    for i, (heading, body) in enumerate(appendix_sections):
        doc.add_paragraph(heading, style="Heading 2")
        render_chapter_markdown(doc, body, FIGURE_MAP)
        if i < len(appendix_sections) - 1:
            add_page_break(doc)

    out_path = os.path.join(os.path.dirname(__file__), "IARS-Dissertation.docx")
    doc.save(out_path)
    print("Saved:", out_path)
    print("Paragraphs:", len(doc.paragraphs), "Tables:", len(doc.tables))


if __name__ == "__main__":
    main()
